### ISSUE TITLE
nvcc warning : option 'host-compilation' has been deprecated and is ignored

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#394]
```
What steps will reproduce the problem?
1. Fresh installed BT 5 R2
2. NVIDIA Linux Display Drivers 295.40
3. NVIDIA CUDA Toolkit 4.1

What is the expected output? What do you see instead?
root@bt:~/pyrit/cpyrit_cuda# python setup.py build
running build
running build_ext
Compiling CUDA module using nvcc 4.1, V0.2.1221...
Executing '/opt/cuda/bin/nvcc -m32 --host-compilation C -Xcompiler "-fPIC" 
--ptx ./_cpyrit_cudakernel.cu'
nvcc warning : option 'host-compilation' has been deprecated and is ignored
Building modules...
building 'cpyrit._cpyrit_cuda' extension
creating build
creating build/temp.linux-i686-2.6
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall 
-Wstrict-prototypes -fPIC -I/opt/cuda/include -I/usr/include/python2.6 -c 
_cpyrit_cuda.c -o build/temp.linux-i686-2.6/_cpyrit_cuda.o -Wall 
-fno-strict-aliasing -DVERSION="0.4.1-dev (svn r308)"
creating build/lib.linux-i686-2.6
creating build/lib.linux-i686-2.6/cpyrit
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions 
build/temp.linux-i686-2.6/_cpyrit_cuda.o -lcrypto -lcuda -lz -o 
build/lib.linux-i686-2.6/cpyrit/_cpyrit_cuda.so


What version of the product are you using? On what operating system?
I have two NVIDIA GeForce GTX 285 and I am using the newest Linux Display 
Driver with the CUDA Toolkit 4.1

Please provide any additional information below.
The nvidia installation went fine without any errors. Also the basic pyrit 
installation (upgrade to 4.0.1) went fine.
Pyrit simply won't detect my gpus. I tried the same thing before on Ubuntu 
11.10 and had the exact same problem. Now I installed BT 5 and it won't work 
either.
```

Original issue reported on code.google.com by `mcposs...@gmail.com` on 11 Apr 2012 at 9:27

**Comment by Bu5h1d0** [comment]
I'm having this same issue. 

Latest rolling Kali Linux 64bit. 
GPU: GTX 1060 & Intel HD Graphics 530 (Skylake GT2) 
i7-6700HQ
16 GB Ram

Pyrit installed fine but Cpyrit won't build correctly.

Tried Cuda 8.0 from Nvidia, install went fine for that, uninstalled that and tried the Cuda from the Kali repo and that is actually the same as Nvidia's site which that installed fine also. Not sure where the problem lies with this but cannot build and install Cpyrit. 

running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.44...
Executing '/usr/local/cuda/bin/nvcc -m64 --host-compilation C -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc fatal : Unknown option '-host-compilation'
Traceback (most recent call last):
File "setup.py", line 175, in <module>
setup(**setup_args)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
self.run_command(cmd_name)
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 100, in run
subprocess.check_call(nvcc_cmd, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/l

**Comment by muorfad** [comment]
I have the same problem Bu5h1d0 . I use Kali 2016.2 x64. I upgrade to 4.8.0, I install from terminal nvidia 375.26. I had some problems installing cuda 8.0.44 but I finally made it. I install pyrit 0.4.0 and when I try to install cpyrit 0.4.0 I cannot build and install.  I couldn't find any other solution. I think its Python problem. We can talk through Skype if u want to find a solution. Hope someone find a solution.

**Comment by muorfad** [comment]
Tomorrow I'll post here and some pics cause I'm from cell phone right now.

**Comment by dizcza** [comment]
@muorfad ,
could you please post here your solution for the problem with `Unknown option '-host-compilation'`, described by @Bu5h1d0 ?

**Comment by AlexCAPS** [comment]
I tried to replace the `nvcc_cmd = NVCC + bit_flag + ' --host-compilation C'\` to `nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8'\` in setup.py and build was successful!

It looks like good job =)

```
$ optirun pyrit list_cores
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CUDA-Device #1 'GeForce GT 620M''
#2:  'CPU-Core (SSE2)'
#3:  'CPU-Core (SSE2)'
#4:  'CPU-Core (SSE2)'

```

**Comment by JPaulMora** [comment]
Hello, @AlexCAPS what version of Pyrit did you have to change this? I couldn't find the deprecated flag in the latest code (master branch).

**Comment by AlexCAPS** [comment]
Hello, @JPaulMora
I use a Pyrit 0.4.0 (downloaded from https://code.google.com/archive/p/pyrit/downloads)

**Comment by JPaulMora** [comment]
Oh, I see. I will close this Issue then, since it's fixed in the latest code.
